volumes:
  pg_data:
  static:
  media:

networks:
  kittygram_network:
    driver: bridge

services:
  postgres:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_network
    restart: always

  backend:
    image: kubyshin/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - postgres
    networks:
      - kittygram_network
    restart: always

  frontend:
    image: kubyshin/kittygram_frontend:latest
    volumes:
      - static:/static
    networks:
      - kittygram_network
    restart: always

  gateway:
    image: kubyshin/kittygram_gateway:latest
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram_network
    restart: always

